### ISSUE TITLE
expansion of the black box with esc-current

### ISSUE THREAD

**Issue by Devil-IdT** [rotorflight/rotorflight-blackbox#23]
would it also be possible to store the current from the esc in the black box? i'll attach a picture

![current_in_blackbox](https://github.com/rotorflight/rotorflight-blackbox/assets/64803366/6d8e5245-1d9c-453c-a41f-aba91bc8e345)

**Comment by rotorflight** [comment]
This is now implemented in the firmware.

**Comment by rotorflight** [comment]
done
