### ISSUE TITLE
Add encoding for new BB log items 

### ISSUE THREAD

**Issue by rotorflight** [rotorflight/rotorflight-blackbox#31]
There are new log items in the firmware, like ESC and BEC data. The support for these fields should be added to BB too.

**Comment by rotorflight** [comment]
All log fields (items) should be known by the BB Explorer.

**Comment by rtlopez** [comment]
Hi @rotorflight, I'm adding new fields to blackbox viewer and meet small issues
1. ESC RPM is actually eRPM in log, and it's value has to be converted according to number of motor poles, but I'm not sure if the intention is to show RPM or eRPM.
2. there is missing RPM data for Esc2 https://github.com/rotorflight/rotorflight-firmware/pull/133/files#diff-97bfca89118cc758fd1576b948ef1cbb5f5f03b4c309cd8236af75a776ca22d1R1337

I will create firmware PR, but please clarify first.
You can also verify names and units I'm going to add in this commit https://github.com/rtlopez/rotorflight-blackbox/pull/4/commits/b3c94efa0e53b5e85db7cee52f3bd72694dd9990, let me know if it is fine.

Cheers
